server:
  #port: 9091
  port: ${port:9091}

spring:
  application:
    name: user-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db3
    username: root
    password: root

mybatis:
  type-aliases-package: com.dxx.user.pojo

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
      #注册多台
  #      defaultZone: http://127.0.0.1:10086/eureka,http://127.0.0.1:10087/eureka

  instance:
    #更倾向使用ip地址，而不是host名
    prefer-ip-address: true
    #ip地址
    ip-address: 127.0.0.1
    #续约时间，默认30秒
    lease-renewal-interval-in-seconds: 5
    #服务失效时间，默认90秒
    lease-expiration-duration-in-seconds: 5
test: hehe
